/*
 * ScoreTableApplet.java
 *
 * Created on December 17, 2003, 10:40 PM
 */

package com.giogo.game;

import com.giogo.Applet;

/**
 *
 * @author  inexum
 */
public class ScoreTableApplet extends Applet 
{
    /** Initializes the applet ScoreTableApplet */
    public void init() 
    {
        super.init();
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "name", "value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        add(jTable1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void update(Object obj) 
    {
        String[] row = (String[])obj;
        javax.swing.table.TableModel model = jTable1.getModel();
        int rowCount = model.getRowCount();
        for(int rIndex = 0; rIndex < rowCount; rIndex++)
        {
            String name = (String)model.getValueAt(rIndex, 0);
            if(name == null)
            {
                model.setValueAt(row[0], rIndex, 0);
                model.setValueAt(row[1], rIndex, 1);
                break;
            }
            if(name.equals(row[0]))
            {
                model.setValueAt(row[1],rIndex,1);
                break;
            }
        }
        repaint();
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
